### ISSUE TITLE
Another heap-buffer-overflow vulnerability

### ISSUE THREAD

**Issue by fouzhe** [objectcomputing/OpenDDS#1848]
There is a heap-buffer-overflow vulnerability in OpenDDS.

OS: Ubuntu 16.04 LTS
Compiler: Clang 5.0 along with AddressSanitizer

Here is the ASAN report:
```
=================================================================
==1522766==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x7fe64a8fc800 at pc 0x0000004f3c1c bp 0x7fe64b0fa7c0 sp 0x7fe64b0f9f70
READ of size 2 at 0x7fe64a8fc800 thread T3
    #0 0x4f3c1b in __asan_memcpy /root/CL/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:466
    #1 0x7fe6524d4d88 in ACE_OS::memcpy(void*, void const*, unsigned long) /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/OS_NS_string.inl:42:10
    #2 0x7fe6524d4d88 in OpenDDS::DCPS::Serializer::smemcpy(char*, char const*, unsigned long) /root/fouzhe/OpenDDS-coverage/dds/DCPS/Serializer.cpp:51
    #3 0x54dc4b in OpenDDS::DCPS::Serializer::doread(char*, unsigned long, bool, unsigned long) /root/fouzhe/OpenDDS-coverage/DevGuideExamples/DCPS/Messenger/../../../dds/DCPS/Serializer.inl:53:13
    #4 0x54dc4b in OpenDDS::DCPS::Serializer::buffer_read(char*, unsigned long, bool) /root/fouzhe/OpenDDS-coverage/DevGuideExamples/DCPS/Messenger/../../../dds/DCPS/Serializer.inl:103
    #5 0x7fe65323a46d in OpenDDS::DCPS::operator>>(OpenDDS::DCPS::Serializer&, unsigned short&) /root/fouzhe/OpenDDS-coverage/dds/DCPS/RTPS/../../../dds/DCPS/Serializer.inl:863:5
    #6 0x7fe65323a46d in OpenDDS::DCPS::operator>>(OpenDDS::DCPS::Serializer&, OpenDDS::RTPS::Parameter&) /root/fouzhe/OpenDDS-coverage/dds/DCPS/RTPS/RtpsCoreTypeSupportImpl.cpp:6381
    #7 0x7fe65323990b in OpenDDS::DCPS::operator>>(OpenDDS::DCPS::Serializer&, OpenDDS::RTPS::ParameterList&) /root/fouzhe/OpenDDS-coverage/dds/DCPS/RTPS/RtpsCoreTypeSupportImpl.cpp:5213:16
    #8 0x7fe6535272d5 in OpenDDS::RTPS::decode_parameter_list(OpenDDS::DCPS::ReceivedDataSample const&, OpenDDS::DCPS::Serializer&, unsigned char const&, OpenDDS::RTPS::ParameterList&) /root/fouzhe/OpenDDS-coverage/dds/DCPS/RTPS/Sedp.cpp:3525:16
    #9 0x7fe6535241a0 in OpenDDS::RTPS::Sedp::Reader::data_received(OpenDDS::DCPS::ReceivedDataSample const&) /root/fouzhe/OpenDDS-coverage/dds/DCPS/RTPS/Sedp.cpp:3564:12
    #10 0x7fe65260dc4b in OpenDDS::DCPS::ReceiveListenerSet::data_received(OpenDDS::DCPS::ReceivedDataSample const&, OpenDDS::DCPS::GUID_t const&) /root/fouzhe/OpenDDS-coverage/dds/DCPS/transport/framework/ReceiveListenerSet.cpp:140:15
    #11 0x7fe65254e2f2 in OpenDDS::DCPS::DataLink::data_received_i(OpenDDS::DCPS::ReceivedDataSample&, OpenDDS::DCPS::GUID_t const&, std::set<OpenDDS::DCPS::GUID_t, OpenDDS::DCPS::GUID_tKeyLessThan, std::allocator<OpenDDS::DCPS::GUID_t> > const&, OpenDDS::DCPS::ReceiveListenerSet::ConstrainReceiveSet) /root/fouzhe/OpenDDS-coverage/dds/DCPS/transport/framework/DataLink.cpp:726:19
    #12 0x7fe65254d124 in OpenDDS::DCPS::DataLink::data_received(OpenDDS::DCPS::ReceivedDataSample&, OpenDDS::DCPS::GUID_t const&) /root/fouzhe/OpenDDS-coverage/dds/DCPS/transport/framework/DataLink.cpp:653:3
    #13 0x7fe653a39caf in OpenDDS::DCPS::RtpsUdpReceiveStrategy::deliver_sample_i(OpenDDS::DCPS::ReceivedDataSample&, OpenDDS::RTPS::Submessage const&) /root/fouzhe/OpenDDS-coverage/dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp:397:16
    #14 0x7fe653a378dc in OpenDDS::DCPS::RtpsUdpReceiveStrategy::deliver_sample(OpenDDS::DCPS::ReceivedDataSample&, ACE_INET_Addr const&) /root/fouzhe/OpenDDS-coverage/dds/DCPS/transport/rtps_udp/RtpsUdpReceiveStrategy.cpp:338:3
    #15 0x7fe653a4433e in OpenDDS::DCPS::TransportReceiveStrategy<OpenDDS::DCPS::RtpsTransportHeader, OpenDDS::DCPS::RtpsSampleHeader>::handle_simple_dds_input(int) /root/fouzhe/OpenDDS-coverage/dds/DCPS/transport/rtps_udp/../../../../dds/DCPS/transport/framework/TransportReceiveStrategy_T.cpp:206:9
    #16 0x7fe6520f1989 in ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >::notify_handle(int, unsigned long, ACE_Handle_Set&, ACE_Event_Handler*, int (ACE_Event_Handler::*)(int)) /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/Select_Reactor_T.cpp:828:22
    #17 0x7fe6520f144c in ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >::dispatch_io_set(int, int&, int, ACE_Handle_Set&, ACE_Handle_Set&, int (ACE_Event_Handler::*)(int)) /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/Select_Reactor_T.cpp:1212:13
    #18 0x7fe6520f0ce2 in ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >::dispatch_io_handlers(ACE_Select_Reactor_Handle_Set&, int&, int&) /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/Select_Reactor_T.cpp:1270:13
    #19 0x7fe6520f025f in ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >::dispatch(int, ACE_Select_Reactor_Handle_Set&) /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/Select_Reactor_T.cpp:1374:22
    #20 0x7fe6520e319c in ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >::handle_events_i(ACE_Time_Value*) /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/Select_Reactor_T.cpp:1465:15
    #21 0x7fe6520e319c in ACE_Select_Reactor_T<ACE_Reactor_Token_T<ACE_Token> >::handle_events(ACE_Time_Value*) /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/Select_Reactor_T.cpp:1441
    #22 0x7fe65003c546 in ACE_Reactor::run_reactor_event_loop(int (*)(ACE_Reactor*)) /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/Reactor.cpp:220:49
    #23 0x7fe6520db4d8 in OpenDDS::DCPS::ReactorTask::svc() /root/fouzhe/OpenDDS-coverage/dds/DCPS/ReactorTask.cpp:158:15
    #24 0x7fe6520dbe05 in virtual thunk to OpenDDS::DCPS::ReactorTask::svc() /root/fouzhe/OpenDDS-coverage/dds/DCPS/ReactorTask.cpp
    #25 0x7fe65005567c in ACE_Task_Base::svc_run(void*) /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/Task.cpp:267:29
    #26 0x7fe650055fe0 in ACE_Thread_Adapter::invoke_i() /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/Thread_Adapter.cpp:163:22
    #27 0x7fe650055e90 in ACE_Thread_Adapter::invoke() /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/Thread_Adapter.cpp:98:16
    #28 0x7fe64ffa396d in ace_thread_adapter /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/Base_Thread_Adapter.cpp:126:45
    #29 0x7fe64fa326b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
    #30 0x7fe64ec5c4dc in clone /build/glibc-e6zv40/glibc-2.23/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:109

0x7fe64a8fc800 is located 0 bytes to the right of 6553600-byte region [0x7fe64a2bc800,0x7fe64a8fc800)
allocated by thread T0 here:
    #0 0x5415b0 in operator new[](unsigned long, std::nothrow_t const&) /root/CL/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:101
    #1 0x7fe64ffee947 in ACE_New_Allocator::malloc(unsigned long) /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/Malloc_Allocator.cpp:115:5
    #2 0x7fe653a48b83 in OpenDDS::DCPS::Cached_Allocator_With_Overflow<char [65536], ACE_Thread_Mutex>::Cached_Allocator_With_Overflow(unsigned long) /root/fouzhe/OpenDDS-coverage/dds/DCPS/transport/rtps_udp/../../../../dds/DCPS/Cached_Allocator_With_Overflow_T.h:68:70

Thread T3 created by T0 here:
    #0 0x461fed in pthread_create /root/CL/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:317
    #1 0x7fe65001182c in ACE_OS::thr_create(void* (*)(void*), void*, long, unsigned long*, unsigned long*, long, void*, unsigned long, ACE_Base_Thread_Adapter*, char const**) /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/OS_NS_Thread.cpp:3911:3
    #2 0x7fe65005f4a8 in ACE_Thread::spawn(void* (*)(void*), void*, long, unsigned long*, unsigned long*, long, void*, unsigned long, ACE_Thread_Adapter*, char const**) /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/Thread.inl:90:10
    #3 0x7fe650058ff9 in ACE_Thread_Manager::spawn_i(void* (*)(void*), void*, long, unsigned long*, unsigned long*, long, int, void*, unsigned long, ACE_Task_Base*, char const**) /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/Thread_Manager.cpp:634:22
    #4 0x7fe650059822 in ACE_Thread_Manager::spawn_n(unsigned long, void* (*)(void*), void*, long, long, int, ACE_Task_Base*, unsigned long*, void**, unsigned long*, char const**) /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/Thread_Manager.cpp:752:17
    #5 0x7fe6500554e9 in ACE_Task_Base::activate(long, int, int, long, int, ACE_Task_Base*, unsigned long*, void**, unsigned long*, unsigned long*, char const**) /root/fouzhe/OpenDDS-coverage/ACE_wrappers/ace/Task.cpp:157:23
    #6 0x7fe6520da635 in OpenDDS::DCPS::ReactorTask::open(void*) /root/fouzhe/OpenDDS-coverage/dds/DCPS/ReactorTask.cpp:86:7
    #7 0x7fe65262bf07 in OpenDDS::DCPS::TransportImpl::create_reactor_task(bool) /root/fouzhe/OpenDDS-coverage/dds/DCPS/transport/framework/TransportImpl.cpp:116:33
    #8 0x7fe653a55713 in OpenDDS::DCPS::RtpsUdpTransport::configure_i(OpenDDS::DCPS::RtpsUdpInst&) /root/fouzhe/OpenDDS-coverage/dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp:457:3
    #9 0x7fe653a54605 in OpenDDS::DCPS::RtpsUdpTransport::RtpsUdpTransport(OpenDDS::DCPS::RtpsUdpInst&) /root/fouzhe/OpenDDS-coverage/dds/DCPS/transport/rtps_udp/RtpsUdpTransport.cpp:40:10

SUMMARY: AddressSanitizer: heap-buffer-overflow /root/CL/llvm/projects/compiler-rt/lib/asan/asan_interceptors.cc:466 in __asan_memcpy
Shadow bytes around the buggy address:
  0x0ffd495178b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffd495178c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffd495178d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffd495178e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0ffd495178f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0ffd49517900:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ffd49517910: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ffd49517920: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ffd49517930: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ffd49517940: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ffd49517950: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==1522766==ABORTING
```

Also, this crash was found in the project through Jul 26 (commit `d2eb16718881be1061efae95f6cbd6e9cc2e6b90`).

**Comment by mitza-oci** [comment]
What was the input data for this one?

**Comment by fouzhe** [comment]
@mitza-oci Sorry, the input cannot be found, but the bug was a reality.

**Comment by mitza-oci** [comment]
Is it still a problem now that #1844 is merged?
