### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: no OpenDDS_DCPS_Javad in java.library.path

### ISSUE THREAD

**Issue by ranbi666** [objectcomputing/OpenDDS#3910]
I am using Windows 10 with JDK 8,  An error occurred when I run "run_test.pl"
 WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
Start Publisher
Exception in thread "main" java.lang.UnsatisfiedLinkError: no OpenDDS_DCPS_Javad in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod

WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
        at OpenDDS.DCPS.TheParticipantFactory.loadNativeLib(TheParticipantFactory.java:34)WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod

WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
        at OpenDDS.DCPS.TheParticipantFactory.<clinit>(TheParticipantFactory.java:21)
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
        at TestPublisher.main(TestPublisher.java:32)
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
Start Subscriber
Exception in thread "main" java.lang.UnsatisfiedLinkError: no OpenDDS_DCPS_Javad in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1122)
        at OpenDDS.DCPS.TheParticipantFactory.loadNativeLib(TheParticipantFactory.java:34)
        at OpenDDS.DCPS.TheParticipantFactory.<clinit>(TheParticipantFactory.java:21)
        at TestSubscriber.main(TestSubscriber.java:29)
ERROR: publisher returned 1
ERROR: subscriber returned 1
INFO: E:\AboutDDS\OpenDDS/bin/DCPSInfoRepo being killed.
test FAILED.

**Comment by mitza-oci** [comment]
Do you have the library `OpenDDS_DCPS_Javad.dll` from building OpenDDS?  If not, it needs to be built.  If so, the directory that it's in needs to be on the `PATH` so that the JVM can load the library.

**Comment by chengxuyuancn** [comment]
你好，请问一下您是怎么解决的这个报错，是如何构建的，我是在ubuntu中报错no OpenDDS_DCPS_Javad in java.library.path，我不知道应该如何构建它

**Comment by iguessthislldo** [comment]
> Hello, may I ask how you solved this error and how you built it? I got an error message "no OpenDDS_DCPS_Javad in java.library.path" in Ubuntu and I don't know how to build it.

On Ubuntu it would be `LD_LIBRARY_PATH` instead of `PATH`.

**Comment by chengxuyuancn** [comment]
> > 您好，请问您是如何解决此错误的以及您是如何构建它的？我在 Ubuntu 中收到错误消息“no OpenDDS_DCPS_Javad in java.library.path”，我不知道如何构建它。
> 
> 在 Ubuntu 上，它将代替 .`LD_LIBRARY_PATH``PATH`

我之前遇到的报错是“no OpenDDS_DCPS_Java in java.library.path”，在找到libOpenDDS_DCPS_Java.so并引入后解决了这个报错，现在的“no OpenDDS_DCPS_Javad in java.library.path”我分析是程序找不到libOpenDDS_DCPS_Javad.so，但是我的opendds安装目录路径中没有OpenDDS_DCPS_Javad相关的.so文件，是我的安装方法出现了问题吗？我在构建opendds时用到了./configure --java命令

**Comment by ranbi666** [comment]
> no OpenDDS_DCPS_Javad in java.library.path
有点太久远了，想不起来了。我重新编译一下试试。

**Comment by chengxuyuancn** [comment]
> > no OpenDDS_DCPS_Javad in java.library.path
> > 有点太久远了，想不起来了。我重新编译一下试试。

好的，谢谢哥

**Comment by ranbi666** [comment]
> > > java.library.path 中没有 OpenDDS_DCPS_Javad
> > > 有点太久了，想不起来了。我重新编译一下试试。
> 
> 好的，谢谢哥

我使用opendds 3.28.1, ubuntu 24.04环境下编译,并没有遇到这个问题
编译手顺:

```
sudo apt-get install libace-dev 
sudo apt-get install libssl-dev
sudo apt-get install default-jdk
./configure --java
make
source setenv.sh
cd java/tests/messenger/
./run_test.pl
**省略很多执行log***
DataReaderListenerImpl.on_subscription_matched
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethodV
	at DDS._DomainParticipantFactoryTAOPeer.delete_participant(Native Method)
	at TestSubscriber.main(TestSubscriber.java:142)
WARNING in native method: JNI call made without checking exceptions when required to from CallObjectMethodV
	at DDS._DomainParticipantFactoryTAOPeer.delete_participant(Native Method)
	at TestSubscriber.main(TestSubscriber.java:142)
WARNING in native method: JNI call made without checking exceptions when required to from CallObjectMethodV
	at DDS._DomainParticipantFactoryTAOPeer.delete_participant(Native Method)
	at TestSubscriber.main(TestSubscriber.java:142)
Subscriber exiting
INFO: /home/nfore/opendds/OpenDDS-3.28.1/bin/DCPSInfoRepo being killed.
InfoRepo_Shutdown: shutting down on signal 15
test PASSED.
```

**Comment by mitza-oci** [comment]
@chengxuyuancn please open a new issue or discussion if you still have questions (which can link to this one).  This issue was closed a long time ago.
